# Generated by Django 5.2.3 on 2025-06-23 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dexterityassessment',
            name='advanced_skills_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Advanced skill - Total score'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='air_cleaner_assembly',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Air cleaner assembly'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='basic_skills_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Basic skill - Total score'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='defect_identification',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Defect identification'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='deflashing',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Deflashing'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='insert_loading_1',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Insert loading - 1'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='insert_loading_2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Insert loading - 2'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='material_identification',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Material identification'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='memory_test',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Memory test'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='mind_hand_coordination',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Mind & hand co-ordination'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='msa_test',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='MSA TEST'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='nerve_stability',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Nerve stability testing'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='overall_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Overall Score'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='painting',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Painting'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='pick_place_sequence',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Pick & Place material in sequence'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='pick_right_material',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Pick right material with right quantity'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='safety_test',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Safety test'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='screw_assembly',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Screw assembly'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='test_1s_2s',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='1S & 2S test'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='test_1s_2s_ball',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='1S & 2S test (Ball)'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='visual_inspection',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Visual inspection'),
        ),
        migrations.AlterField(
            model_name='dexterityassessment',
            name='written_test',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Written test'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(choices=[('operator', 'Operator'), ('technician', 'Technician'), ('supervisor', 'Supervisor'), ('engineer', 'Engineer')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.CharField(choices=[('production', 'Production'), ('quality', 'Quality'), ('maintenance', 'Maintenance'), ('logistics', 'Logistics')], max_length=50, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='plant',
            field=models.CharField(choices=[('plant-a', 'Plant A'), ('plant-b', 'Plant B'), ('plant-c', 'Plant C')], max_length=50, verbose_name='Plant'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='day',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Final Score'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='operation_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Operation Name'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='perf_n',
            field=models.CharField(blank=True, max_length=20, verbose_name='Perf-N'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='personnel_certified',
            field=models.BooleanField(default=False, verbose_name='Personnel Certified'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='pro_n',
            field=models.CharField(blank=True, max_length=20, verbose_name='PRO-N'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='production',
            field=models.CharField(blank=True, max_length=50, verbose_name='Production'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='quantity',
            field=models.CharField(blank=True, max_length=20, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='scope',
            field=models.CharField(blank=True, max_length=100, verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='su_status',
            field=models.CharField(blank=True, max_length=10, verbose_name='S/U Status'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='supervisor_approved',
            field=models.BooleanField(default=False, verbose_name='Supervisor Approved'),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='weight',
            field=models.CharField(blank=True, max_length=20, verbose_name='Weight'),
        ),
    ]
