# Generated by Django 5.2.3 on 2025-06-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dexterityassessment_advanced_skills_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='after_ojt_dept',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Department After OJT'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='area_of_work',
            field=models.CharField(max_length=255, verbose_name='Area of Work'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(choices=[('operator', 'Operator'), ('technician', 'Technician'), ('supervisor', 'Supervisor'), ('engineer', 'Engineer')], max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.CharField(choices=[('production', 'Production'), ('quality', 'Quality'), ('maintenance', 'Maintenance'), ('logistics', 'Logistics')], max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='Employee Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overall_percent',
            field=models.FloatField(default=0, verbose_name='Overall Percentage'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='plant',
            field=models.CharField(choices=[('plant-a', 'Plant A'), ('plant-b', 'Plant B'), ('plant-c', 'Plant C')], max_length=100, verbose_name='Plant'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=100, verbose_name='Skill Level'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sl1_marks',
            field=models.IntegerField(default=0, verbose_name='SL1 Marks'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sl1_status',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], max_length=50, null=True, verbose_name='SL1 Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sl2_marks',
            field=models.IntegerField(default=0, verbose_name='SL2 Marks'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sl2_ojt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SL2 OJT Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sl2_status',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], max_length=50, null=True, verbose_name='SL2 Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sl3_status',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], max_length=50, null=True, verbose_name='SL3 Status'),
        ),
    ]
