# Generated by Django 5.2.3 on 2025-06-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employee_after_ojt_dept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='area_of_work',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Area of Work'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, choices=[('operator', 'Operator'), ('technician', 'Technician'), ('supervisor', 'Supervisor'), ('engineer', 'Engineer')], max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.CharField(blank=True, choices=[('production', 'Production'), ('quality', 'Quality'), ('maintenance', 'Maintenance'), ('logistics', 'Logistics')], max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Employee Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overall_percent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Overall Percentage'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='plant',
            field=models.CharField(blank=True, choices=[('plant-a', 'Plant A'), ('plant-b', 'Plant B'), ('plant-c', 'Plant C')], max_length=100, null=True, verbose_name='Plant'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=100, null=True, verbose_name='Skill Level'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sl1_marks',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='SL1 Marks'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sl2_marks',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='SL2 Marks'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='training_days',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Training Days'),
        ),
    ]
