# Generated by Django 5.2.3 on 2025-06-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_employee_age_alter_employee_area_of_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='plant',
            field=models.CharField(blank=True, choices=[('plant-a', 'Plant A'), ('plant-b', 'Plant B'), ('plant-c', 'Plant C'), ('central', 'Central')], max_length=100, null=True, verbose_name='Plant'),
        ),
    ]
