# Generated by Django 5.2.3 on 2025-06-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employee_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.CharField(blank=True, choices=[('special_painter', 'Special Painter'), ('standard_room', 'standard room'), ('stores', 'Stores'), ('sub_contract_area', 'Sub contract area'), ('tool_room', 'TOOL ROOM'), ('tqc', 'TQC'), ('tvsm_qre', 'TVSM QRE'), ('unit_1', 'Unit-1'), ('plant_2', 'Plant-2'), ('plant_3', 'Plant-3'), ('product_audit', 'Product audit'), ('purchase', 'Purchase'), ('quality', 'Quality'), ('r_and_d', 'R & D'), ('safety', 'SAFETY'), ('sap', 'SAP'), ('security', 'Security'), ('material_loader', 'Material loader'), ('mold_change', 'Mold change'), ('molding', 'Molding'), ('mould_development', 'Mould development'), ('npd', 'NPD'), ('paint_plant', 'Paint Plant'), ('ped', 'PED'), ('personnel', 'Personnel'), ('plant_1', 'Plant-1'), ('despatch', 'Despatch'), ('dock_audit', 'Dock audit'), ('finance', 'Finance'), ('get', 'GET'), ('hrd', 'HRD'), ('incoming_inspection', 'Incoming inspection'), ('line_inspector', 'Line inspector'), ('maintenance', 'Maintenance'), ('marketing', 'MARKETING'), ('assy', 'Assy'), ('bmw_area', 'BMW Area'), ('bmw_inspection', 'BMW Inspection'), ('bop', 'BOP'), ('civil', 'Civil'), ('cnc_operator', 'CNC Operator'), ('conti_fi', 'Conti FI'), ('data_entry', 'Data entry')], max_length=100, null=True, verbose_name='Department'),
        ),
    ]
