# Generated by Django 5.2.3 on 2025-06-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_employee_after_ojt_dept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, choices=[('1l', '1L'), ('2l', '2L'), ('3l', '3L'), ('ge', 'GE'), ('sw', 'SW'), ('ta', 'TA')], max_length=100, null=True, verbose_name='Category'),
        ),
    ]
