# Generated by Django 5.2.3 on 2025-06-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_employee_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Supervisor Name'),
        ),
    ]
