# Generated by Django 5.2.3 on 2025-06-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_employee_supervisor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('sl0', 'SL 0'), ('sl1', 'SL 1'), ('sl2', 'SL 2'), ('sl3', 'SL 3')], default='sl0', max_length=100, null=True, verbose_name='Skill Level'),
        ),
    ]
